# numPy

For fundamental Linear Algebra, welcome to check this [colab](https://colab.research.google.com/github/drvinceknight/Python-Mathematics-Handbook/blob/master/02-Linear-algebra-with-Numpy.ipynb).<br>
And thanks Dr. Vince Knight for this simple colab.

import re

html = """
<p><table border="1" cellspacing="0" cellpadding="3">
<tbody>
<tr>
<th style="text-align: left; background-color: #ccc1d9;" width="23%">Year</th>
<th style="text-align: left; background-color: #ccc1d9;" width="77%">History</th>
</tr>
<tr class="odd">
<td>1979</td>
<td>Statistics (STAT) Programme was set up as an individual programme of study.</td>
</tr>
<tr class="odd">
<td>1981</td>
<td>Establishment of Division of Statistics at Graduate School, CUHK.</td>
</tr>
<tr class="odd">
<td>1982</td>
<td>Foundation of the Department. 17 students were enrolled in the first year with Prof. Howell Tong as the chairman</td>
</tr>
<tr class="odd">
<td>1986</td>
<td>Professor Sik-yum Lee assumed the duty of chairman of the Department.</td>
</tr>
<tr class="odd">
<td>1993</td>
<td>Professor Nai Ng Chan became the third chairman of the Department.</td>
</tr>
<tr class="odd">
<td>1994</td>
<td>The Department office relocated from Science Centre to the current site &#8211; Lady Shaw Building.</td>
</tr>
<tr class="odd">
<td></td>
<td>Professor Wing-hung Wong served as the chairman of the Department.</td>
</tr>
<tr class="odd">
<td>1998</td>
<td>Professor Yeh Lam succeeded Professor Wing-hung Wong and took up the chairmanship of the Department.</td>
</tr>
<tr class="odd">
<td>1999</td>
<td>Risk Management Science (RMSC) stream was launched. Professor Kim Hung Li assumed the chairmanship for one year.</td>
</tr>
<tr class="odd">
<td>2000</td>
<td>Professor Jian Qing Fan served as the seventh chairman of the Department.</td>
</tr>
<tr class="odd">
<td></td>
<td>Risk Management Science (RMSC) was expanded to be an individual programme of study.</td>
</tr>
<tr class="odd">
<td></td>
<td>The first batch of students majoring in RMSC was enrolled.</td>
</tr>
<tr class="odd">
<td>2004</td>
<td>Professor Ngai Hang Chan was inaugurated as the Department chairman.</td>
</tr>
<tr class="odd">
<td>2009</td>
<td>The Department first offered a double-major programme in Quantitive Finance and Risk Management Science (QRFM).</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>Corresponding to the new 3-3-4 curriculum, the undergraduate programme in Statistics joined Science Faculty broad-based admission scheme.</td>
</tr>
<tr class="odd">
<td>2013</td>
<td>Professor Qi Man Shao was inaugurated as the Department chairman.</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>Professor Xinyuan Song was inaugurated as the Department chair.</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>B.Sc. in Computational Data Science was launched.</td>
</tr>
<tr class="odd">
<td>2024</td>
<td>M.Sc. in Advanced Studies in Statistics and Data Science was launched.</td>
</tr>
<tr class="odd">
<td>2024</td>
<td>Professor Junhui Wang was inaugurated as the Department chair.</td>
</tr>
</tbody>
</table>
</p>

"""
    Extract unique chair professor names (Prof./Professor) from HTML text.
    Supports Unicode, apostrophes, accents, initials, and is case-insensitive.
    """
    # This pattern:
    # - (?i): case-insensitive
    # - (Prof\.|Professor): Prof. OR Professor (any case)
    # - \s+: at least one space (can extend to optional if desired)
    # - Name: starts with capital, includes letters, hyphens, apostrophes, accents, dots, and spaces
    # - Looks ahead for a word boundary or punctuation
    pattern = r'(?i)(Prof\.|Professor)\s+([A-Z][\w\'\-\.\sÀ-ÖØ-öø-ÿ]*[A-Za-zÀ-ÖØ-öø-ÿ])\b'
    matches = re.findall(pattern, html, flags=re.UNICODE)
    names = []
    seen = set()
    for prefix, name in matches:
        # Remove accidental trailing punctuation
        name = re.sub(r'[\.,;:]+$', '', name.strip())
        full_name = f"{prefix} {name}"
        if full_name not in seen:
            names.append(full_name)
            seen.add(full_name)
    return names


import re

def extract_professor_names(https://drive.google.com/file/d/1yuUys0F2AQd8QZu73q5rOWDnsxpWHWcd/view):
    """
    Extract unique chair professor names (Prof./Professor) from HTML text.
    Supports Unicode, apostrophes, accents, initials, and is case-insensitive.
    """
    # This pattern:
    # - (?i): case-insensitive
    # - (Prof\.|Professor): Prof. OR Professor (any case)
    # - \s+: at least one space (can extend to optional if desired)
    # - Name: starts with capital, includes letters, hyphens, apostrophes, accents, dots, and spaces
    # - Looks ahead for a word boundary or punctuation
    pattern = r'(?i)(Prof\.|Professor)\s+([A-Z][\w\'\-\.\sÀ-ÖØ-öø-ÿ]*[A-Za-zÀ-ÖØ-öø-ÿ])\b'
    matches = re.findall(pattern, html, flags=re.UNICODE)
    names = []
    seen = set()
    for prefix, name in matches:
        # Remove accidental trailing punctuation
        name = re.sub(r'[\.,;:]+$', '', name.strip())
        full_name = f"{prefix} {name}"
        if full_name not in seen:
            names.append(full_name)
            seen.add(full_name)
    return names



In [ ]:
import numpy as np

In [ ]:
import re

html_content = """

<p><table border="1" cellspacing="0" cellpadding="3">

<tbody>

<tr>

<th style="text-align: left; background-color: #ccc1d9;" width="23%">Year</th>

<th style="text-align: left; background-color: #ccc1d9;" width="77%">History</th>

</tr>

<tr class="odd">

<td>1979</td>

<td>Statistics (STAT) Programme was set up as an individual programme of study.</td>

</tr>

<tr class="odd">

<td>1981</td>

<td>Establishment of Division of Statistics at Graduate School, CUHK.</td>

</tr>

<tr class="odd">

<td>1982</td>

<td>Foundation of the Department. 17 students were enrolled in the first year with Prof. Howell Tong as the chairman</td>

</tr>

<tr class="odd">

<td>1986</td>

<td>Professor Sik-yum Lee assumed the duty of chairman of the Department.</td>

</tr>

<tr class="odd">

<td>1993</td>

<td>Professor Nai Ng Chan became the third chairman of the Department.</td>

</tr>

<tr class="odd">

<td>1994</td>

<td>The Department office relocated from Science Centre to the current site &#8211; Lady Shaw Building.</td>

</tr>

<tr class="odd">

<td></td>

<td>Professor Wing-hung Wong served as the chairman of the Department.</td>

</tr>

<tr class="odd">

<td>1998</td>

<td>Professor Yeh Lam succeeded Professor Wing-hung Wong and took up the chairmanship of the Department.</td>

</tr>

<tr class="odd">

<td>1999</td>

<td>Risk Management Science (RMSC) stream was launched. Professor Kim Hung Li assumed the chairmanship for one year.</td>

</tr>

<tr class="odd">

<td>2000</td>

<td>Professor Jian Qing Fan served as the seventh chairman of the Department.</td>

</tr>

<tr class="odd">

<td></td>

<td>Risk Management Science (RMSC) was expanded to be an individual programme of study.</td>

</tr>

<tr class="odd">

<td></td>

<td>The first batch of students majoring in RMSC was enrolled.</td>

</tr>

<tr class="odd">

<td>2004</td>

<td>Professor Ngai Hang Chan was inaugurated as the Department chairman.</td>

</tr>

<tr class="odd">

<td>2009</td>

<td>The Department first offered a double-major programme in Quantitive Finance and Risk Management Science (QRFM).</td>

</tr>

<tr class="odd">

<td>2012</td>

<td>Corresponding to the new 3-3-4 curriculum, the undergraduate programme in Statistics joined Science Faculty broad-based admission scheme.</td>

</tr>

<tr class="odd">

<td>2013</td>

<td>Professor Qi Man Shao was inaugurated as the Department chairman.</td>

</tr>

<tr class="odd">

<td>2018</td>

<td>Professor Xinyuan Song was inaugurated as the Department chair.</td>

</tr>

<tr class="odd">

<td>2022</td>

<td>B.Sc. in Computational Data Science was launched.</td>

</tr>

<tr class="odd">

<td>2024</td>

<td>M.Sc. in Advanced Studies in Statistics and Data Science was launched.</td>

</tr>

<tr class="odd">

<td>2024</td>

<td>Professor Junhui Wang was inaugurated as the Department chair.</td>

</tr>

</tbody>

</table>

</p>

"""

def decode_html_entities(text):
    # Covers key HTML entities found in your sample and some common extras
    text = text.replace('&#8211;', '–').replace('&ndash;', '–')
    text = text.replace('&nbsp;', ' ')
    text = text.replace('&amp;', '&')
    # Add more as needed for your HTML
    return text

def extract_chair_professors(html_content):
    # Step 1: Decode known HTML entities
    text_content = decode_html_entities(html_content)
    # Step 2: Remove HTML tags (robust for simple HTML)
    text_content = re.sub(r'<[^>]+>', ' ', text_content)

    # Step 3: Regex for professor names (now supports initials, hyphens, apostrophes, dots, and non-ASCII letters)
    # - Names: sequences of capitalized words, initials with dots, hyphens, apostrophes, and Unicode letters
    # - At least two "name parts" after the title
    name_part = r"(?:[A-ZÀ-ÖØ-öø-ÿĀ-ž][a-zA-ZÀ-ÖØ-öø-ÿĀ-ž'\-]*|[A-Z]\.)"
    professor_pattern = (
        r'\b(?:Prof\.|Professor)\s+' +
        name_part + r'(?:\s+' + name_part + r'){1,4}'
    )
    matches = re.findall(professor_pattern, text_content)

    # Step 4: Clean up whitespace and deduplicate while preserving order
    cleaned = []
    seen = set()
    for m in matches:
        name = ' '.join(m.split())
        if name not in seen:
            cleaned.append(name)
            seen.add(name)
    return cleaned

if __name__ == "__main__":
    professors = extract_chair_professors(html_content)
    for prof in professors:
        print(prof)

Prof. Howell Tong
Professor Sik-yum Lee
Professor Nai Ng Chan
Professor Wing-hung Wong
Professor Yeh Lam
Professor Kim Hung Li
Professor Jian Qing Fan
Professor Ngai Hang Chan
Professor Qi Man Shao
Professor Xinyuan Song
Professor Junhui Wang


In [ ]:
# array creation
print(np.array([4, 5, 6]))
print(np.array([[7, 8, 9], [10, 11, 12]]))

[4 5 6]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# array dimension
m = np.array([[7, 8, 9], [10, 11, 12]])
m.shape

(2, 3)

In [ ]:
# sequence
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n # seq(0, 30, 2) --> c(0, ..., 30)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# reshape the array / matrix
#n = n.reshape(3, 5) # reshape array to be 3x5
n.resize(3, 5) # in-place
n

NameError: name 'n' is not defined

In [ ]:
# interpolation
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
# 1-matrix
print(np.ones([3, 2]))
print(np.ones([3,2,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
# 0-matrix
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# diagonalization / get diagonal
y = np.diag([1, 2, 3, 4])
print(y)
print(np.diag(y))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


In [ ]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
# repeat arrays
print(np.array([1, 2, 3] * 3))
print(np.repeat([1, 2, 3], 3))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


# Numpy as Matrix Calculator

In [ ]:
# arithmetics (element-wise)
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y, x-y, x*y, x/y, x**2)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [1 4 9]


In [ ]:
x.T

array([1, 2, 3])

In [ ]:
print(x.dot(y))
print(np.dot(x,y))

32
32


In [ ]:
# Inner / Dot Product
x.dot(y) # (x^T)y
np.inner(x, y)

np.int64(32)

In [ ]:
# Outer Product
np.outer(x, y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [ ]:
# transpose
z = np.array([y, y**2])
print(z, z.shape)
print(z.T, z.T.shape)

[[ 4  5  6]
 [16 25 36]] (2, 3)
[[ 4 16]
 [ 5 25]
 [ 6 36]] (3, 2)


In [ ]:
# matrix multiplication
print(np.matmul(z, z.T))
print(z.dot(z.T))

[[  77  405]
 [ 405 2177]]
[[  77  405]
 [ 405 2177]]


In [ ]:
# inverse

from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
print(ainv)

NameError: name 'np' is not defined

In [ ]:
# check AA^(-1) = I
print(np.allclose(np.dot(a, ainv), np.eye(2)))

True


In [ ]:
np.dot(a, ainv)== np.eye(2)

array([[ True,  True],
       [False, False]])

In [ ]:
# type of matrix
print(z.dtype)
print(z.astype('f'))

int64
[[ 4.  5.  6.]
 [16. 25. 36.]]


In [ ]:
# Math functions
a = np.array([-4, -2, 1, 3, 5])
print(a.sum(), a.max(), a.min(), a.mean(), a.std(), a.argmax(), a.argmin())

3 5 -4 0.6 3.2619012860600183 4 0


In [ ]:
# combining arrays
p = np.ones([2, 3])
print(np.vstack([p, 2*p]))
print(np.hstack([p, 2*p]))

[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]


# Matrix Slicing

In [ ]:
# Array
s = np.arange(13)**2
print(s[0], s[4], s[-1], s[1:5], s[-4:])
print(s[-5::-2]) # array[start:stop:stepsize]

0 16 144 [ 1  4  9 16] [ 81 100 121 144]
[64 36 16  4  0]


In [ ]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
# Matrix
r = np.arange(36)
r.resize((6, 6))
print(r)
print(r[2, 2], r[3, 3:6], r[:2, :-1], r[-1, ::2], r[r > 30])
r[r > 30] = 30
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
14 [21 22 23] [[ 0  1  2  3  4]
 [ 6  7  8  9 10]] [30 32 34] [31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Simple Random Numbers
Ref in numpy: [here](https://numpy.org/doc/stable/reference/random/index.html)

In [ ]:
import numpy as np
temp = np.random.choice(49, 6, replace=False)
np.sort(temp)

array([ 2,  8,  9, 36, 40, 46])

In [ ]:
np.random.seed(9394)
temp = np.random.choice(49, 6, replace=False)
print(np.sort(temp))
temp = np.random.choice(49, 6, replace=False)
print(np.sort(temp))
temp = np.random.choice(49, 6, replace=False)
print(np.sort(temp))

[17 27 28 32 36 41]
[ 5 13 33 36 37 43]
[ 4  6 15 16 36 39]
